#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= "test"
require "pathname"
require "cypress-rails"

env_file = Pathname.new(CypressRails.config.dir).join('cypress/env.rb')
if env_file.exist?
  require env_file
else
  require Pathname.new(CypressRails.config.dir).join("config/environment")
end

command = ARGV[0]
case command
when "init"
  CypressRails::Init.new.call
when "open"
  CypressRails::Open.new.call
when "run"
  passed = CypressRails::Run.new.call
  exit 1 unless passed
end
